license="MIT License"
[[mods]]
modId="spig"
version="${file.jarVersion}"
displayName="Spider Pig"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spider-pig"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Spider Pig Mod'''
[[dependencies.spig]]
    modId="neoforge"
    type="required"
    versionRange="[21.11.0-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.spig]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.11,1.22)"
    ordering="NONE"
    side="BOTH"
